### ISSUE TITLE
Add persistence for configuration settings

### ISSUE THREAD

**Issue by wisygig** [massgo/league#102]
We can edit slack configuration variables after #97, but the current method of changing these variables does not persist over different server sessions.

For this configuration data, when would be the appropriate time to read this data? The current structure of the application factory doesn't have a clean insert point (configuration data is read from the environment before the database is activated).

**Comment by hndrewaall** [comment]
If we allow the module to load absent environmental info (so, if no env vars are set), and also support dynamic reconfiguration, then we can do something similar to what we do for the automatically generated root user (which, frankly, is kind of a brutal hack):

https://github.com/massgo/league/blob/master/app/league/app.py#L90
https://github.com/massgo/league/blob/master/app/league/admin/utils.py#L6

**Comment by wisygig** [comment]
After a bit of reading, I decided to implement this following the pattern described in [http://flask.pocoo.org/docs/0.12/config/](url).
