### ISSUE TITLE
Add new metrics to dashboard

### ISSUE THREAD

**Issue by hndrewaall** [massgo/league#114]
Some new metrics:

- Kyu Killer - defeats of kyu players by a dan players
- Dan Demolisher - defeats of dan players by kyu players
- Stoned - handicap stones given

Should be enough to just add to template and `episode_stats` function

**Comment by hndrewaall** [comment]
@njritter anything else lightweight you had in mind? I think these are simple enough to do without asynchronous tasks, and I don't think we really need to wait for the episode view

**Comment by njritter** [comment]
Those are the 3 most requested stats/achievements to track! Starting here seems good.

**Comment by MattClarke131** [comment]
Template is [here](https://github.com/massgo/league/blob/master/app/league/templates/dashboard/dashboard.html)
episode_stats is [here](https://github.com/massgo/league/blob/master/app/league/dashboard/models.py) on line 225.

**Comment by hndrewaall** [comment]
https://github.com/massgo/league/blob/master/app/league/dashboard/models.py#L225

^ deep link :)

**Comment by sartak** [comment]
Also nice to have would be displaying number of games played so far, and maybe % win by Black

**Comment by hndrewaall** [comment]
@sartak this has been added in #148 !

Closing this, since the bulk of this was implemented in #115

**Comment by hndrewaall** [comment]
Oops, I misread your request. Well, I added a thing anyway. What you mention would be useful for season stats, which don't exist at all (yet)
