### ISSUE TITLE
Add configurable text/banners and dynamic templates

### ISSUE THREAD

**Issue by wisygig** [massgo/league#142]
@hndrewaall said:
> I want to have configurable text/banners, at least sufficient to tell people roughly what's happening
> so that'll likely involve adding some settings to a config page
> and editing templates to load content dynamically

**Comment by wisygig** [comment]
@hndrewaall Do you have a wireframe for what you want? I'll add the backend support for now (extra admin config page + update admin utils to load site settings)

**Comment by hndrewaall** [comment]
I do not. Do what makes sense to you and I'm sure it'll be a good start.
