### ISSUE TITLE
Add Slack integration

### ISSUE THREAD

**Issue by hndrewaall** [massgo/league#50]
A basic (and useful) Slack integration would be to simply post game results as they are added (much like @njritter already does manually)

**Comment by hndrewaall** [comment]
@hwchen do you think you'll be able to work on this soonish?

**Comment by hwchen** [comment]
Unsure. My weekend is packed, and work unfortunately is cutting into fun
time. If I get into a good morning schedule soon, I would be able to give
more assurances. But as of now I can't guarantee

**Comment by hndrewaall** [comment]
npnp. I was thinking of giving this to Jason

**Comment by wisygig** [comment]
Like https://api.slack.com/incoming-webhooks ?

**Comment by hndrewaall** [comment]
Yessir. Can do raw HTTP, but I'm sure there are also a plethora of slack "SDKs" available. Some research into this may prove fruitful. Can post candidates here

**Comment by hndrewaall** [comment]
Channel/API token should be configurable. Can start with "hardcoded" values in the app config, but really should be exposed as a config view (probably admin-only)

**Comment by hndrewaall** [comment]
(config view/dynamic configuration will require lots more changes, so I def recommend starting with just hardcoding in config)

**Comment by hndrewaall** [comment]
oh btw, "hardcoded" config should be overridable by env vars, since (until we get config panel) this is the only practical way to deploy

**Comment by wisygig** [comment]
Added an extension which wraps a simple messenger; it requires knowledge of the Slack webhook url and the target channel, which are stored as environment variables. Testing would be welcome!
